version: "3.9"

services:
  react-app:
    build:
      context: ../UI/datacube-UI
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000" # React app runs on port 3000 internally
    environment:
      - NODE_ENV=development # Use development for local testing
    networks:
      - app-network

  django-app:
    build:
      context: .. #/django-app
      dockerfile: Dockerfile.dev
    container_name: django_app
    ports:
      - "8000:8000" # Django runs on port 8000 via Gunicorn
    env_file:
      - ../.env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Bind to localhost:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-app
      - django-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
